server:
  port: 7777
  forward-headers-strategy: framework
spring:
  application:
    name: authservice
  # Active profiles
  profiles:
    active: secret
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://config-server:8088}"

# OpenAPI SwaggerUI config
springdoc:
  version: '@springdoc.version@'